Feature/drink milk shake mission #79
DeveloperAcademy-POSTECH/MC3-Team13-RiceCake pull request #84
Opened 2022-07-28 14:45 UTC by David-ShinDJ

ReView 내용 전부 수정해서 다시 PR올립니다

2022-07-28 15:05 UTC, bee712 approved these changes

2022-07-28 16:14 UTC, seodam-hst reviewed
빌드가 안 됩니다 🆘 
리뷰 내용 확인해주세요!

2022-07-28 16:14 UTC, seodam-hst commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +        let longPressedGesture: UILongPressGestureRecognizer = UILongPressGestureRecognizer(target: self, action: #selector(longPressedStarw(_:)))
밑에 함수는 Straw로 수정되었는데 여기 함수는 아직도 Starw로 남아있네요. 
함수 사용된 곳 전부 수정해주세요! 

지금 빌드도 안 됩니다.

2022-07-28 16:14 UTC, seodam-hst commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +    var twinkleCircle: UIView!
아까 보여주셨을 때는 두 원의 색이 다르고 크기는 비슷해 보였는데,
왜 변수 이름이 littleCircle, twinkleCircle인가요?

2022-07-28 16:14 UTC, seodam-hst commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +                .cancelled:
case문 들여쓰기가 원래 이게 맞나요?

2022-07-28 16:14 UTC, seodam-hst commented on RiceCake/RiceCake/Game/StageNotificationCenter.swift
> +    static let drawDrinkMission = Notification.Name("drawDrinkMission")
Drink -> DrinkMilkShake로 바꿔주시면 알아보기 더 쉬울 것 같습니다.

2022-07-28 16:19 UTC, seodam-hst requested changes
빌드가 안 됩니다. 💥 
리뷰 내용 확인해주세요!

2022-07-28 17:35 UTC, David-ShinDJ commented
Simulator Build 확인했습니다 
줄간격 스페이스 수정했습니다
CIrcle Name 색깔로지정 해놧어요 ㅋㅋ 
머지좀 해줘요 이제~

2022-07-29 05:06 UTC, seodam-hst approved these changes
땅땅 승인!

2022-07-29 05:11 UTC, JungYunseong approved these changes
Lint warning 2개 있습니다.
그냥 간단한거라 저가 수정했습니다.
다음엔 신경써서 해주세요

2022-07-29 05:43 UTC, David-ShinDJ commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +    @objc func longPressedStraw(_ sender: UILongPressGestureRecognizer) {
리뷰반영해서 커밋했습니다
커밋넘버 2119bae573909d9c31893689abbf77e964b10ff2

2022-07-29 05:43 UTC, David-ShinDJ commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +        let longPressedGesture: UILongPressGestureRecognizer = UILongPressGestureRecognizer(target: self, action: #selector(longPressedStarw(_:)))
리뷰반영해서 커밋했습니다
커밋넘버 2119bae573909d9c31893689abbf77e964b10ff2

2022-07-29 05:43 UTC, David-ShinDJ commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +    var twinkleCircle: UIView!
리뷰반영해서 커밋했습니다
커밋넘버 2119bae573909d9c31893689abbf77e964b10ff2

2022-07-29 05:43 UTC, David-ShinDJ commented on RiceCake/RiceCake/Game/CafeStage/DrinkMilkShake/MilkShakeViewController.swift
> +                .cancelled:
리뷰반영해서 커밋했습니다
커밋넘버 2119bae573909d9c31893689abbf77e964b10ff2

2022-07-29 05:43 UTC, David-ShinDJ commented on RiceCake/RiceCake/Game/StageNotificationCenter.swift
> +    static let drawDrinkMission = Notification.Name("drawDrinkMission")
리뷰반영해서 커밋했습니다
커밋넘버 2119bae573909d9c31893689abbf77e964b10ff2

2022-07-29 05:44 UTC, merged